#!/bin/bash

venv='../j1939_venv'
output=j1939_venv.requirements.txt

if [[ ! -d ${venv} ]]; then
	echo "* Creating venv ${venv}"
	python -m venv ${venv}
fi

if [[ ! -r ${venv}/bin/pip-compile ]]; then
	echo "* Installing pip-tools"
	${venv}/bin/pip install pip-tools > /dev/null 2>&1
fi

echo "* Pip compiling ${output}"
${venv}/bin/pip-compile ./*.in --output-file ${output} > /dev/null 2>&1

echo "* Installing requirements"
${venv}/bin/pip install -r ${output} > /dev/null 2>&1


# EOF
